basics:
  site_title: Draper Startup House Da Nang
  site_base_url: 'https://connectinvietnam.com'
  contact_email: danang@draperstartuphouse.com
  phone_number: 84907144561
  address_html: >-
    <p>38 Do Bi Street<br />My An ward, Ngu Hanh Son District<br />Da Nang,
    550000&nbsp;</p><p>&nbsp;</p>
social:
  facebook_url: 'https://www.facebook.com/dshdanang/'
  instagram_url: 'https://www.instagram.com/dshdanang/'
  instagram_handle: '@dshdanang'
  twitter_url: 'https://twitter.com/dshglobal'
  twitter_handle: '@dshglobal'
  youtube_url: 'https://www.youtube.com/channel/UCKoQpAKfCRFRCJvtFzfHWaQ'
  linkedin_url: 'https://www.linkedin.com/company/draperstartuphouse/'
  eventbrite_url: 'https://www.eventbrite.com/o/draper-startup-house-da-nang-33050536537'
seo:
  fb_app_id:
  keywords:
    - Da Nang
    - Da Nang coworking
    - startup
    - Da Nang startup
    - Da Nang digital nomads
    - Da Nang hostel
  description: Draper Startup House connects you to Da Nang's startup ecosystem.
colors:
  white_color: '#f2f2f2'
  gray_color: '#555555'
  lighter_gray_color: '#556655'
  yellow_color: '#ffcc09'
  navy_blue_color: '#204270'
fonts:
  fonts_code_block: <link href="/styles/fonts.css" rel="stylesheet">
  body_font_family: '''ProximaNovaRegular'', sans-serif;'
  body_alt_font_family: '''P22UndergroundRegular'', sans-serif;'
  header_bold_font_family: '''ProximaNovaBlack'', sans-serif;'
  header_font_family: '''ProximaNovaCond'', sans-serif;'
  accent_font_family: '''AlternateGothicRegular'', sans-serif;'
configuration:
  google_tag_manager_code_block:
  google_analytics_code_block:
  form_submission_handler_code_block:
  flexbox_framework_code_block: >-
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css">